version : '3'
services:
  shadowsocksr:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 1024000
        hard: 1024000
    ports : 
      - '10080:1080'
    environment: 
      PASSWORD : 'password'
      METHOD: 'aes-128-ctr'
      PROTOCOL: 'auth_aes128_md5'
      PROTOCOLPARAM: '32'
      OBFS: 'tls1.2_ticket_auth_compatible'
      TIMEOUT: '600'
